# © 2025 rndnanthu – Licensed under CC BY-NC 4.0 (https://creativecommons.org/licenses/by-nc/4.0/)
# --- Core Node Imports ---
from .prompt.PromptGenerator import NODE_CLASS_MAPPINGS as PROMPT_NODES, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY
from .colortools.log_color_conversion import NODE_CLASS_MAPPINGS as LOG_NODES, NODE_DISPLAY_NAME_MAPPINGS as LOG_DISPLAY
from .colortools.ColorGradingNode import NODE_CLASS_MAPPINGS as COLOR_NODES, NODE_DISPLAY_NAME_MAPPINGS as COLOR_DISPLAY
from .grain.FilmGrain import NODE_CLASS_MAPPINGS as GRAIN_NODES, NODE_DISPLAY_NAME_MAPPINGS as GRAIN_DISPLAY

# --- Custom Visual Nodes ---
from .colortools.colorspacesim import NODE_CLASS_MAPPINGS as COLORSPACE_NODES, NODE_DISPLAY_NAME_MAPPINGS as COLORSPACE_DISPLAY
from .colortools.autogradepro import NODE_CLASS_MAPPINGS as AUTOGRADE_NODES, NODE_DISPLAY_NAME_MAPPINGS as AUTOGRADE_DISPLAY
from .colortools.ColorAnalysisPlotNode import NODE_CLASS_MAPPINGS as COLORANALYSIS_NODES, NODE_DISPLAY_NAME_MAPPINGS as COLORPLOT_DISPLAY


# === Combine All Node Mappings ===
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(PROMPT_NODES)
NODE_CLASS_MAPPINGS.update(LOG_NODES)
NODE_CLASS_MAPPINGS.update(COLOR_NODES)
NODE_CLASS_MAPPINGS.update(GRAIN_NODES)
NODE_CLASS_MAPPINGS.update(COLORSPACE_NODES)
NODE_CLASS_MAPPINGS.update(AUTOGRADE_NODES)
NODE_CLASS_MAPPINGS.update(COLORANALYSIS_NODES)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(PROMPT_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(LOG_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(COLOR_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(GRAIN_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(COLORSPACE_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(AUTOGRADE_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(COLORPLOT_DISPLAY)

# === Final Exports ===
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']


YELLOW = '\033[93m'
WHITE ='\033[37m'
RESET = '\033[0m'

print(f'{YELLOW}[RNDNANTHU] : {WHITE}THANKS FOR USING{RESET}')
print(f'{YELLOW}[RNDNANTHU] : {WHITE}KINDLY GIVE YOUR SUPPORT TO {YELLOW}RNDNANTHU{RESET}')
